# Generated by Django 4.0.6 on 2022-12-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
                ('is_menu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('vil', models.CharField(choices=[('Tashkent', "Farg'ona"), ('Namangan', 'Andijon'), ("Marg'ilon", 'Sirdaryo'), ('Qashqadaryo', 'Jizzah'), ('Samarqand', 'Buxoro'), ('Qoraqalpoqiston', 'Navoiy')], max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('compain', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=256)),
                ('quvvati', models.CharField(max_length=25)),
                ('silindr', models.IntegerField()),
                ('karobka', models.CharField(max_length=5)),
                ('tezlik', models.CharField(max_length=25)),
                ('gildirak', models.CharField(max_length=6)),
                ('yoqilgi', models.IntegerField()),
                ('uzunlik', models.IntegerField()),
                ('kenglik', models.IntegerField()),
                ('tepalik', models.IntegerField()),
                ('akumlyator', models.CharField(max_length=6)),
                ('telefon', models.CharField(max_length=15)),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAgro.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAgro.product')),
            ],
        ),
    ]
